name: Generate Transcript TXT Only

on:
  workflow_dispatch:
    inputs:
      limit:
        description: "Ölçü limiti (all, -1 ya da pozitif sayı). Tüm parça için 'all' kullanın."
        required: false
        default: "all"
      commit:
        description: "Değişiklikleri commit et (true/false)"
        required: false
        default: "true"

permissions:
  contents: write

concurrency:
  group: gen-txt-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gen-txt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Rebase/push hatalarını önlemek için önce senkronize ol
      - name: Sync main (hard reset)
        run: |
          set -e
          git fetch origin main
          git reset --hard origin/main

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Eski çıktıları temizle
        run: |
          set -e
          rm -f transcript_*.txt transcript_*.json transcript_*.lua transcript_*.abc measure_map_*.md playback_order.txt || true

      - name: Yapı / Debug liste
        run: |
          set -e
          echo "Çalışma dizini (pwd):"; pwd
          echo "--- Root içerik ---"; ls -al
          echo "--- İlk 6 seviye (script ve xml araması) ---"
          find . -maxdepth 6 -type f \( -name "generate_transcript.py" -o -name "HAHA.musicxml" \)

      - name: Script çalıştır
        id: runscript
        env:
          DEBUG_PLAYBACK: "1"
          OBSERVE_REPEATS_AFTER_RETURN: "1"   # D.C./D.S. dönüşünden sonra repeat’leri uygula
        run: |
          set -euo pipefail
          SCRIPT_PATH=$(find . -maxdepth 6 -type f -name "generate_transcript.py" | head -n1 || true)
          if [ -z "${SCRIPT_PATH}" ]; then
            echo "HATA: generate_transcript.py bulunamadı." >&2
            exit 1
          fi
          MUSICXML_PATH=$(find . -maxdepth 6 -type f -name "HAHA.musicxml" | head -n1 || true)
          if [ -z "${MUSICXML_PATH}" ]; then
            echo "HATA: HAHA.musicxml bulunamadı." >&2
            exit 1
          fi

          echo "Script   : ${SCRIPT_PATH}"
          echo "MusicXML : ${MUSICXML_PATH}"
          echo "Limit    : ${{ github.event.inputs.limit }}"

          python "${SCRIPT_PATH}" "${MUSICXML_PATH}" "${{ github.event.inputs.limit }}"

          # Beklenen çıktı
          OUT_TXT="transcript_rh.txt"
          if [ ! -f "$OUT_TXT" ]; then
            echo "HATA: transcript_rh.txt bulunamadı." >&2
            ls -al
            exit 2
          fi

          echo "Çıktı dosyası: $OUT_TXT"
          head -n 25 "$OUT_TXT" || true

          if [ -f playback_order.txt ]; then
            echo "---- playback_order.txt (ilk 50 satır) ----"
            head -n 50 playback_order.txt || true
          fi

          echo "out_txt=${OUT_TXT}" >> $GITHUB_OUTPUT

      - name: Değişiklik kontrol
        id: diffcheck
        run: |
          OUT_TXT="${{ steps.runscript.outputs.out_txt }}"
          if [ -n "$(git status --porcelain "$OUT_TXT")" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit & push
        if: steps.diffcheck.outputs.changed == 'true' && github.event.inputs.commit == 'true'
        run: |
          set -e
          OUT_TXT="${{ steps.runscript.outputs.out_txt }}"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$OUT_TXT"
          git commit -m "chore: auto-generate ${OUT_TXT} (limit=${{ github.event.inputs.limit }})"
          git push origin main
          echo "Commit ve push tamam."

      - name: Artifact yükle
        uses: actions/upload-artifact@v4
        with:
          name: transcripts
          path: |
            ${{ steps.runscript.outputs.out_txt }}
            playback_order.txt
          if-no-files-found: warn
